on:
  workflow_dispatch:

jobs:
  windows-release-build:
    runs-on: windows-latest
    steps:
    - name: Checkout Source for dispatch
      uses: actions/checkout@v3
      with:
        ref: master
        persist-credentials: true
        fetch-depth: 0
    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Find Go Install Location
      shell: pwsh
      run: |
        $go_install_dir = (Get-Command go | Get-Item).Directory.FullName
        Add-Content -Path $env:GITHUB_ENV "MY_GO_INSTALL_DIR=$go_install_dir"
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          curl
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-gpgme
          mingw-w64-x86_64-pkg-config
    - name: Build CSI Proxy
      shell: msys2 {0}
      run: |
        export PATH=${PATH}:`cygpath ${MY_GO_INSTALL_DIR}`
        mingw32-make.exe build
    - name: Get current release for dispatch
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}    
      id: current_release_dispatch
      uses: cardinalby/git-get-release-action@1.2.2
      with:
        tag: latest
    - name: Upload files to GitHub release
      uses: svenstaro/upload-release-action@2.3.0
      with:
        file: 'bin/csi-proxy.exe'
        tag: latest
        overwrite: 'true'
